In [7]:
import xarray as xr
import fsspec
from pathlib import Path
from dask.diagnostics import ProgressBar
import pandas as pd
import numpy as np
import scipy.spatial

In [15]:
def print_era5_vars(ds):
    rows = []
    for name, da in ds.data_vars.items():
        long_name = da.attrs.get("long_name", "")
        units = da.attrs.get("units", "")
        rows.append((name, long_name, units))

    # column widths
    name_w = max(len(r[0]) for r in rows)
    lname_w = max(len(r[1]) for r in rows)
    units_w = max(len(r[2]) for r in rows)

    header = (
        f"{'VAR':<{name_w}} | "
        f"{'LONG NAME':<{lname_w}} | "
        f"{'UNITS':<{units_w}}"
    )
    sep = "-" * len(header)

    print(header)
    print(sep)
    for name, long_name, units in rows:
        print(
            f"{name:<{name_w}} | "
            f"{long_name:<{lname_w}} | "
            f"{units:<{units_w}}"
        )


In [12]:
fs = fsspec.filesystem('gs', token='anon')

In [34]:
ds = xr.open_zarr(
    fs.get_mapper('gs://gcp-public-data-arco-era5/co/single-level-reanalysis.zarr-v2'),
    consolidated=True,
)
print_era5_vars(ds)


/tmp/ipykernel_1059544/879621314.py:1: FutureWarning: In a future version, xarray will not decode the variable 'step' into a timedelta64 dtype based on the presence of a timedelta-like 'units' attribute by default. Instead it will rely on the presence of a timedelta64 'dtype' attribute, which is now xarray's default way of encoding timedelta64 values.
To continue decoding into a timedelta64 dtype, either set `decode_timedelta=True` when opening this dataset, or add the attribute `dtype='timedelta64[ns]'` to this variable on disk.
To opt-in to future behavior, set `decode_timedelta=False`.
  ds = xr.open_zarr(


VAR     | LONG NAME                                                  | UNITS         
-------------------------------------------------------------------------------------
cape    | Convective available potential energy                      | J kg**-1      
d2m     | 2 metre dewpoint temperature                               | K             
hcc     | High cloud cover                                           | (0 - 1)       
istl1   | Ice temperature layer 1                                    | K             
istl2   | Ice temperature layer 2                                    | K             
istl3   | Ice temperature layer 3                                    | K             
istl4   | Ice temperature layer 4                                    | K             
lcc     | Low cloud cover                                            | (0 - 1)       
mcc     | Medium cloud cover                                         | (0 - 1)       
msl     | Mean sea level pressure                     

In [32]:
ds

<xarray.Dataset> Size: 1PB
Dimensions:     (time: 1323648, hybrid: 137, values: 410240)
Coordinates:
  * time        (time) datetime64[ns] 11MB 1900-01-01 ... 2050-12-31T23:00:00
  * hybrid      (hybrid) float64 1kB 1.0 2.0 3.0 4.0 ... 134.0 135.0 136.0 137.0
    step        timedelta64[ns] 8B ...
    valid_time  (time) datetime64[ns] 11MB dask.array<chunksize=(1323648,), meta=np.ndarray>
Dimensions without coordinates: values
Data variables:
    d           (time, hybrid, values) float32 298TB dask.array<chunksize=(1, 1, 410240), meta=np.ndarray>
    t           (time, hybrid, values) float32 298TB dask.array<chunksize=(1, 1, 410240), meta=np.ndarray>
    vo          (time, hybrid, values) float32 298TB dask.array<chunksize=(1, 1, 410240), meta=np.ndarray>
    w           (time, hybrid, values) float32 298TB dask.array<chunksize=(1, 1, 410240), meta=np.ndarray>
Attributes: (12/14)
    Conventions:               CF-1.7
    GRIB_centre:               ecmf
    GRIB_centreDescription:    European Centre for Medium-Range Weather Forec...
    GRIB_edition:              2
    GRIB_subCentre:            0
    history:                   2022-10-09T17:47 GRIB to CDM+CF via cfgrib-0.9...
    ...                        ...
    pangeo-forge:recipe_hash:  ed5fbf407898def1e27d4e8965c2cdaa01b7ea8f2ac2e1...
    pangeo-forge:version:      0.9.1
    valid_time_start:          1940-01-01
    last_updated:              2026-01-16 01:58:25.664990+00:00
    valid_time_stop:           2025-10-31
    valid_time_stop_era5t:     2026-01-10

In [19]:
ds = xr.open_zarr(
    fs.get_mapper('gs://gcp-public-data-arco-era5/co/model-level-wind.zarr-v2'),
    consolidated=True,
)
ds


/tmp/ipykernel_1059544/421711231.py:1: FutureWarning: In a future version, xarray will not decode the variable 'step' into a timedelta64 dtype based on the presence of a timedelta-like 'units' attribute by default. Instead it will rely on the presence of a timedelta64 'dtype' attribute, which is now xarray's default way of encoding timedelta64 values.
To continue decoding into a timedelta64 dtype, either set `decode_timedelta=True` when opening this dataset, or add the attribute `dtype='timedelta64[ns]'` to this variable on disk.
To opt-in to future behavior, set `decode_timedelta=False`.
  ds = xr.open_zarr(


<xarray.Dataset> Size: 1PB
Dimensions:     (time: 1323648, hybrid: 137, values: 410240)
Coordinates:
  * time        (time) datetime64[ns] 11MB 1900-01-01 ... 2050-12-31T23:00:00
  * hybrid      (hybrid) float64 1kB 1.0 2.0 3.0 4.0 ... 134.0 135.0 136.0 137.0
    step        timedelta64[ns] 8B ...
    valid_time  (time) datetime64[ns] 11MB dask.array<chunksize=(1323648,), meta=np.ndarray>
Dimensions without coordinates: values
Data variables:
    d           (time, hybrid, values) float32 298TB dask.array<chunksize=(1, 1, 410240), meta=np.ndarray>
    t           (time, hybrid, values) float32 298TB dask.array<chunksize=(1, 1, 410240), meta=np.ndarray>
    vo          (time, hybrid, values) float32 298TB dask.array<chunksize=(1, 1, 410240), meta=np.ndarray>
    w           (time, hybrid, values) float32 298TB dask.array<chunksize=(1, 1, 410240), meta=np.ndarray>
Attributes: (12/14)
    Conventions:               CF-1.7
    GRIB_centre:               ecmf
    GRIB_centreDescription:    European Centre for Medium-Range Weather Forec...
    GRIB_edition:              2
    GRIB_subCentre:            0
    history:                   2022-10-09T17:47 GRIB to CDM+CF via cfgrib-0.9...
    ...                        ...
    pangeo-forge:recipe_hash:  ed5fbf407898def1e27d4e8965c2cdaa01b7ea8f2ac2e1...
    pangeo-forge:version:      0.9.1
    valid_time_start:          1940-01-01
    last_updated:              2026-01-16 01:58:25.664990+00:00
    valid_time_stop:           2025-10-31
    valid_time_stop_era5t:     2026-01-10

In [20]:
ds["hybrid"].values

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137.])

In [22]:
print([*ds.coords])
print([*ds.data_vars])


['hybrid', 'step', 'time', 'valid_time']
['d', 't', 'vo', 'w']


In [23]:
ds = xr.open_zarr(
    fs.get_mapper('gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3'),
    consolidated=True,
)

In [28]:
ds['temperature'].sel(level=250)

<xarray.DataArray 'temperature' (time: 1323648, latitude: 721, longitude: 1440)> Size: 5TB
dask.array<getitem, shape=(1323648, 721, 1440), dtype=float32, chunksize=(1, 721, 1440), chunktype=numpy.ndarray>
Coordinates:
  * time       (time) datetime64[ns] 11MB 1900-01-01 ... 2050-12-31T23:00:00
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
    level      int64 8B 250
Attributes:
    long_name:      Temperature
    short_name:     t
    standard_name:  air_temperature
    units:          K

In [30]:
for t in pd.date_range("2020-01-01T00:00:00", periods=24, freq="H"):
    one_hour = ds["temperature"].sel(level=250, time=t)
    arr = one_hour.values                  # (542080,)
    print(t, arr)

/tmp/ipykernel_1059544/1803027966.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  for t in pd.date_range("2020-01-01T00:00:00", periods=24, freq="H"):


2020-01-01 00:00:00 [[208.00505 208.00505 208.00505 ... 208.00505 208.00505 208.00505]
 [207.94408 207.94408 207.9452  ... 207.9435  207.9435  207.94408]
 [207.78506 207.78621 207.78679 ... 207.78223 207.78336 207.78394]
 ...
 [227.25282 227.25397 227.2551  ... 227.25111 227.25168 227.25282]
 [227.33888 227.33888 227.34001 ... 227.33774 227.33774 227.33888]
 [227.45229 227.45229 227.45229 ... 227.45229 227.45229 227.45229]]
2020-01-01 01:00:00 [[207.91045 207.91045 207.91045 ... 207.91045 207.91045 207.91045]
 [207.80559 207.80559 207.80559 ... 207.80388 207.80502 207.80502]
 [207.68364 207.68477 207.68535 ... 207.68193 207.68193 207.6825 ]
 ...
 [227.30013 227.30013 227.30013 ... 227.29785 227.29898 227.29898]
 [227.41695 227.41809 227.41809 ... 227.4158  227.41695 227.41695]
 [227.5315  227.5315  227.5315  ... 227.5315  227.5315  227.5315 ]]
2020-01-01 02:00:00 [[207.85403 207.85403 207.85403 ... 207.85403 207.85403 207.85403]
 [207.77766 207.77881 207.77881 ... 207.77766 207.77766 2